apiVersion: apps/v1
kind: Deployment
metadata:
  name: runtime-manager
spec:

  replicas: 1

  selector:
    matchLabels:
      app: runtime-manager

  template:
    metadata:
      labels:
        app: runtime-manager
    spec:
      serviceAccountName: runtime-manager
      containers:
        - name: runtime-manager
          image: k8s-runtime-manager:1.0
          ports:
            - containerPort: 8080
